### ISSUE TITLE
你好，请教一下，这个支持英文数据吗？uie-base-en处理英文数据的结果一直为空

### ISSUE THREAD

**Issue by zjms** [taishan1994/pytorch_uie_re#1]

**Comment by zjms** [comment]
你的好像是不可以的。https://github.com/heiheiyoyo/uie_pytorch/blob/main/uie_predictor.py代码中构造prompt时有对  if self._is_en:的判断，你代码中没有，只支持中文。

**Comment by taishan1994** [comment]
> 你的好像是不可以的。[https://github.com/heiheiyoyo/uie_pytorch/blob/main/uie_predictor.py代码中构造prompt时有对](https://github.com/heiheiyoyo/uie_pytorch/blob/main/uie_predictor.py%E4%BB%A3%E7%A0%81%E4%B8%AD%E6%9E%84%E9%80%A0prompt%E6%97%B6%E6%9C%89%E5%AF%B9) if self._is_en:的判断，你代码中没有，只支持中文。

是的，是根据其之前的代码改的，后面没有更了。
